# Generated by Django 3.2.5 on 2021-07-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_description_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='title_on_map',
        ),
    ]
